name: Python application test with github acations
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3
      uses: actions/setup-python@v1
      with: 
       python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test
    - name: Lint with python
      run: |
        make lint
    - name: Format code with Python black
      run: |
        make format
    
